---
  - hosts: php
    become: true
    roles:
      - install-appd-php-agent

    vars_files:
      - "../vars/common.yml"


  - hosts: db
    become: true
    roles:
      - install-appd-database-agent

    vars_files:
      - "../vars/common.yml"